version: 2.1
orbs:
  architect: giantswarm/architect@4.25.0

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          context: "architect"
          executor: "app-build-suite"
          name: "package and push linkerd2-multicluster-link-app chart"
          app_catalog: "giantswarm-catalog"
          app_catalog_test: "giantswarm-test-catalog"
          chart: "linkerd2-multicluster-link-app"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
