apiVersion: v2
appVersion: stable-2.12.4
description: |
  A helm chart containing the resources to enable mirroring
  of services from a remote cluster.

  Warning: The purpose of this chart is just to support the `linkerd
  multicluster link` CLI command, which also produces the
  `cluster-credentials` secret and the Link CR, which are not found in this
  chart. Therefore this chart is not a replacement for that command, and
  shouldn't be used as-is unless you really know what you're doing ;-)
kubeVersion: ">=1.21.0-0"
dependencies:
  - name: partials
    version: 0.1.0
icon: https://s.giantswarm.io/app-icons/linkerd2/2/logo_dark.svg
name: "linkerd-multicluster-link"
version: 0.10.0
restrictions:
  clusterSingleton: false
  fixedNamespace: linkerd-multicluster
annotations:
  application.giantswarm.io/team: team-cabbage
