# -- Registry switch
# Do not overwrite this as it is automatically set based on the installation region
image:
  registry: quay.io
# -- Docker image for the Service mirror component (uses the Linkerd controller
# image)
controllerImage: giantswarm/linkerd2-controller
# -- Tag for the Service Mirror container Docker image
controllerImageVersion: stable-2.12.4
# -- Toggle support for mirroring headless services
enableHeadlessServices: false
gateway:
  probe:
    # -- The port used for liveliness probing
    port: 4191
# -- Log level for the Multicluster components
logLevel: info
# -- Node selectors for the Service mirror pod
nodeSelector: {}
# -- Resources for the Service mirror container
resources: {}
# -- Number of times update from the remote cluster is allowed to be requeued
# (retried)
serviceMirrorRetryLimit: 3
# -- User id under which the Service Mirror shall be ran
serviceMirrorUID: 2103
# -- Name of the target cluster that's going to be linked
targetClusterName: ""
# -- Tolerations for the Service mirror pod
tolerations: {}

# -- Create RoleBindings to associate ServiceAccount of target cluster Service
# Mirror to the control plane PSP resource. This requires that `enabledPSP` is
# set to true on the extension and control plane install. Note PSP has been
# deprecated since k8s v1.21
enablePSP: true

# -- Settings needed in order to enable the link to watch services
target:
  enabled: false
  api: ""
  CA: ""
  token: ""
  gateway:
    ip: ""
    port: "4143"
    portProbe: "4191"
