---
apiVersion: v1
kind: Service
metadata:
  name: probe-gateway-{{.Values.target.name | default .Values.clusterID}}
  namespace: {{.Values.namespace}}
  labels:
    mirror.linkerd.io/mirrored-gateway: "true"
    mirror.linkerd.io/cluster-name: {{.Values.target.name | default .Values.clusterID}}
spec:
  ports:
  - name: mc-probe
    port: {{.Values.gateway.probe.port}}
    protocol: TCP
