---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: linkerd-service-mirror-access-local-resources-{{.Values.target.name | default .Values.clusterID}}
  labels:
    linkerd.io/extension: multicluster
    linkerd.io/control-plane-component: service-mirror
    mirror.linkerd.io/cluster-name: {{.Values.target.name | default .Values.clusterID}}
rules:
- apiGroups: [""]
  resources: ["endpoints", "services"]
  verbs: ["list", "get", "watch", "create", "delete", "update"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["list", "get", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: linkerd-service-mirror-access-local-resources-{{.Values.target.name | default .Values.clusterID}}
  labels:
    linkerd.io/extension: multicluster
    linkerd.io/control-plane-component: service-mirror
    mirror.linkerd.io/cluster-name: {{.Values.target.name | default .Values.clusterID}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: linkerd-service-mirror-access-local-resources-{{.Values.target.name | default .Values.clusterID}}
subjects:
- kind: ServiceAccount
  name: {{ include "linkerd-service-mirror.serviceAccountName" . }}
  namespace: {{.Values.namespace}}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: linkerd-service-mirror-read-remote-creds-{{.Values.target.name | default .Values.clusterID}}
  namespace: {{.Values.namespace}}
  labels:
      linkerd.io/extension: multicluster
      linkerd.io/control-plane-component: service-mirror
      mirror.linkerd.io/cluster-name: {{.Values.target.name | default .Values.clusterID}}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["cluster-credentials-{{.Values.target.name | default .Values.clusterID}}"]
    verbs: ["list", "get", "watch"]
  - apiGroups: ["multicluster.linkerd.io"]
    resources: ["links"]
    verbs: ["list", "get", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: linkerd-service-mirror-read-remote-creds-{{.Values.target.name | default .Values.clusterID}}
  namespace: {{.Values.namespace}}
  labels:
      linkerd.io/extension: multicluster
      linkerd.io/control-plane-component: service-mirror
      mirror.linkerd.io/cluster-name: {{.Values.target.name | default .Values.clusterID}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: linkerd-service-mirror-read-remote-creds-{{.Values.target.name | default .Values.clusterID}}
subjects:
  - kind: ServiceAccount
    name: {{ include "linkerd-service-mirror.serviceAccountName" . }}
    namespace: {{.Values.namespace}}
{{- if .Values.serviceAccount.create }}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ include "linkerd-service-mirror.serviceAccountName" . }}
  namespace: {{.Values.namespace}}
  labels:
    linkerd.io/extension: multicluster
    linkerd.io/control-plane-component: service-mirror
    mirror.linkerd.io/cluster-name: {{.Values.target.name | default .Values.clusterID}}
{{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    linkerd.io/extension: multicluster
    linkerd.io/control-plane-component: service-mirror
    mirror.linkerd.io/cluster-name: {{.Values.target.name | default .Values.clusterID}}
  name: linkerd-service-mirror-{{.Values.target.name | default .Values.clusterID}}
  namespace: {{.Values.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      linkerd.io/control-plane-component: linkerd-service-mirror
      mirror.linkerd.io/cluster-name: {{.Values.target.name | default .Values.clusterID}}
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        linkerd.io/control-plane-component: linkerd-service-mirror
        mirror.linkerd.io/cluster-name: {{.Values.target.name | default .Values.clusterID}}
    spec:
      containers:
      - args:
        - service-mirror
        - -log-level={{.Values.logLevel}}
        - -event-requeue-limit={{.Values.serviceMirrorRetryLimit}}
        - -namespace={{.Values.namespace}}
        {{- if .Values.enableHeadlessServices }}
        - -enable-headless-services
        {{- end }}
        - -enable-pprof={{.Values.enablePprof | default false}}
        - {{.Values.target.name | default .Values.clusterID}}
        image: "{{.Values.image.registry}}/{{.Values.controllerImage}}:{{.Values.controllerImageVersion}}"
        name: service-mirror
        securityContext:
          runAsUser: {{.Values.serviceMirrorUID}}
        ports:
        - containerPort: 9999
          name: admin-http
      serviceAccountName: {{ include "linkerd-service-mirror.serviceAccountName" . }}
