name: linkerd2-multicluster-source-app
serviceType: managed

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

image:
  registry: quay.io
  name: giantswarm/linkerd2-multicluster-source-app
  tag: v0.0.1
  pullPolicy: IfNotPresent
