{{ if .Values.target.enabled }}
apiVersion: v1
stringData:
  kubeconfig: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: {{ .Values.target.CA | b64enc }}
        server: {{ .Values.target.api }}
      name: {{ .Values.targetClusterName }}
    contexts:
    - context:
        cluster: {{ .Values.targetClusterName }}
        user: linkerd-service-mirror-remote-access-default
      name: {{ .Values.targetClusterName }}
    current-context: {{ .Values.targetClusterName }}
    kind: Config
    preferences: {}
    users:
    - name: linkerd-service-mirror-remote-access-default
      user:
        token: {{ .Values.target.token }}
kind: Secret
metadata:
  name: cluster-credentials-{{.Values.targetClusterName}}
  namespace: {{ .Release.Namespace }}
type: mirror.linkerd.io/remote-kubeconfig
---
apiVersion: multicluster.linkerd.io/v1alpha1
kind: Link
metadata:
  name: {{ .Values.targetClusterName }}
  namespace: {{ .Release.Namespace }}
spec:
  clusterCredentialsSecret: cluster-credentials-{{.Values.targetClusterName}}
  gatewayAddress: {{ .Values.target.gateway.ip | quote }}
  gatewayIdentity: linkerd-gateway.linkerd-multicluster.serviceaccount.identity.linkerd.cluster.local
  gatewayPort: {{ .Values.target.gateway.port | quote }}
  probeSpec:
    path: /ready
    period: 3s
    port: {{ .Values.target.gateway.portProbe | quote }}
  selector:
    matchExpressions:
    - key: mirror.linkerd.io/exported
      operator: Exists
  targetClusterDomain: cluster.local
  targetClusterLinkerdNamespace: linkerd
  targetClusterName: {{ .Values.targetClusterName }}
{{ end }}
